/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Core.Board.Board;
import Core.Board.EnchantedRealm;
import Core.Board.FieryDesert;
import Core.Board.FrozenKingdom;
import Core.Board.IsolatedIsland;
import Core.Shifting.Player;
import Core.Shifting.PlayerMoveable;



/**
 *
 * @author Diogo
 */
public class FrameGame extends javax.swing.JFrame{

    
    /**
     * Creates new form FrameGame
     */
    public FrameGame() {
        initComponents();
        game.requestFocus();
        
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        game = new GUI.Game();
        jPanel1 = new javax.swing.JPanel();
        textBombs = new javax.swing.JLabel();
        textLives = new javax.swing.JLabel();
        textScore = new javax.swing.JLabel();
        titleBombs = new javax.swing.JLabel();
        titlePlayer = new javax.swing.JLabel();
        titleLives = new javax.swing.JLabel();
        titleScore = new javax.swing.JLabel();
        LsaveButton = new javax.swing.JLabel();
        LloadButton = new javax.swing.JLabel();
        LtitleCenarios = new javax.swing.JLabel();
        LfKingdom = new javax.swing.JLabel();
        LfDesert = new javax.swing.JLabel();
        LeRealm = new javax.swing.JLabel();
        LiIsland = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        game.setPreferredSize(new java.awt.Dimension(1000, 1000));
        game.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gameKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout gameLayout = new javax.swing.GroupLayout(game);
        game.setLayout(gameLayout);
        gameLayout.setHorizontalGroup(
            gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );
        gameLayout.setVerticalGroup(
            gameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 726, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 5));
        jPanel1.setForeground(new java.awt.Color(0, 240, 240));
        jPanel1.setToolTipText("");

        textBombs.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        textBombs.setForeground(new java.awt.Color(255, 255, 102));
        textBombs.setText("20");

        textLives.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        textLives.setForeground(new java.awt.Color(255, 255, 102));
        textLives.setText("3");

        textScore.setFont(new java.awt.Font("Sitka Small", 1, 24)); // NOI18N
        textScore.setForeground(new java.awt.Color(255, 255, 102));
        textScore.setText("0");

        titleBombs.setFont(new java.awt.Font("SimHei", 1, 18)); // NOI18N
        titleBombs.setForeground(new java.awt.Color(255, 153, 0));
        titleBombs.setText("Bombs");
        titleBombs.setAlignmentX(0.5F);
        titleBombs.setAutoscrolls(true);

        titlePlayer.setFont(new java.awt.Font("SimHei", 1, 48)); // NOI18N
        titlePlayer.setForeground(new java.awt.Color(255, 102, 102));
        titlePlayer.setText("Player");
        titlePlayer.setAlignmentX(0.5F);
        titlePlayer.setFocusable(false);

        titleLives.setFont(new java.awt.Font("SimHei", 1, 18)); // NOI18N
        titleLives.setForeground(new java.awt.Color(255, 153, 0));
        titleLives.setText("Lives");

        titleScore.setBackground(new java.awt.Color(200, 200, 200));
        titleScore.setFont(new java.awt.Font("SimHei", 1, 24)); // NOI18N
        titleScore.setForeground(new java.awt.Color(255, 153, 0));
        titleScore.setText("Score");

        LsaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/saveButton1.png"))); // NOI18N
        LsaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LsaveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LsaveButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LsaveButtonMousePressed(evt);
            }
        });

        LloadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/loadButton1.png"))); // NOI18N
        LloadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LloadButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LloadButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LloadButtonMousePressed(evt);
            }
        });

        LtitleCenarios.setFont(new java.awt.Font("Symbola", 1, 24)); // NOI18N
        LtitleCenarios.setForeground(new java.awt.Color(139, 66, 103));
        LtitleCenarios.setText("Cenarios:");
        LtitleCenarios.setToolTipText("");

        LfKingdom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/frozen.png"))); // NOI18N
        LfKingdom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LfKingdomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LfKingdomMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LfKingdomMousePressed(evt);
            }
        });

        LfDesert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/desert.png"))); // NOI18N
        LfDesert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LfDesertMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LfDesertMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LfDesertMousePressed(evt);
            }
        });

        LeRealm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/realm.png"))); // NOI18N
        LeRealm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LeRealmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LeRealmMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LeRealmMousePressed(evt);
            }
        });

        LiIsland.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/island.png"))); // NOI18N
        LiIsland.setToolTipText("");
        LiIsland.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LiIslandMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LiIslandMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LiIslandMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(titlePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LtitleCenarios)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(titleScore)
                                        .addComponent(titleLives))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textLives, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(titleBombs)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                    .addComponent(textBombs, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(LsaveButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(LloadButton)))
                            .addComponent(LfKingdom)
                            .addComponent(LfDesert)
                            .addComponent(LeRealm)
                            .addComponent(LiIsland))
                        .addGap(65, 65, 65))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titlePlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleScore)
                    .addComponent(textScore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLives)
                    .addComponent(textLives))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleBombs)
                    .addComponent(textBombs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LtitleCenarios)
                .addGap(18, 18, 18)
                .addComponent(LfKingdom)
                .addGap(18, 18, 18)
                .addComponent(LfDesert)
                .addGap(27, 27, 27)
                .addComponent(LeRealm)
                .addGap(18, 18, 18)
                .addComponent(LiIsland)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LsaveButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LloadButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(game, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(game, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gameKeyPressed
        game.processKey(evt.getKeyCode());
    }//GEN-LAST:event_gameKeyPressed

    private void gameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gameKeyReleased
        game.processKeyRealized(evt.getKeyCode());
        myComponents();
    }//GEN-LAST:event_gameKeyReleased

    private void LsaveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LsaveButtonMouseEntered
        LsaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/saveButton2.png")));
    }//GEN-LAST:event_LsaveButtonMouseEntered

    private void LsaveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LsaveButtonMouseExited
        LsaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/saveButton1.png")));
    }//GEN-LAST:event_LsaveButtonMouseExited

    private void LloadButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LloadButtonMouseEntered
        LloadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/loadButton2.png")));
    }//GEN-LAST:event_LloadButtonMouseEntered

    private void LloadButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LloadButtonMouseExited
        LloadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/loadButton1.png")));
    }//GEN-LAST:event_LloadButtonMouseExited

    private void LloadButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LloadButtonMousePressed
        game.stop();
        Board board=(Board) game.readObject("/board.obj");
        game=new Game(board);
        game.player=(Player) game.readObject("/player.obj");
        game.playerMoveable1=(PlayerMoveable) game.readObject("/playerMov1.obj");
        game.playerMoveable2=(PlayerMoveable) game.readObject("/playerMov2.obj");
        game.general=(PlayerMoveable) game.readObject("/general.obj");
        game.requestFocus();
    }//GEN-LAST:event_LloadButtonMousePressed

    private void LsaveButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LsaveButtonMousePressed
        game.writeObject(game.board, "/board.obj");
        game.writeObject(game.player, "/player.obj");
        game.writeObject(game.playerMoveable1, "/playerMov1.obj");
        game.writeObject(game.playerMoveable2, "/playerMov2.obj");
        game.writeObject(game.general, "/general.obj");
        game.requestFocus();
    }//GEN-LAST:event_LsaveButtonMousePressed

    private void LfKingdomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LfKingdomMouseEntered
        LfKingdom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/frozen2.png")));
    }//GEN-LAST:event_LfKingdomMouseEntered

    private void LfKingdomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LfKingdomMouseExited
        LfKingdom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/frozen.png")));
    }//GEN-LAST:event_LfKingdomMouseExited

    private void LfKingdomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LfKingdomMousePressed
        game.stop();
        initComponents();
        //game=new FrozenKingdom().setVisible(true);
        game=new Game(game.board=new FrozenKingdom());
        //game=new Game(game.player= game.board.getPlayer());
        //game=new Game(game.playerMoveable1=game.board.getPlayerMoveable1());
        //game=new Game(game.playerMoveable2=game.board.getPlayerMoveable2());
        //game=new Game(game.general=game.board.getGeneral());
        game.requestFocus();        
        //game.start();
       
        
    }//GEN-LAST:event_LfKingdomMousePressed

    private void LfDesertMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LfDesertMouseEntered
         LfDesert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/desert2.png")));
    }//GEN-LAST:event_LfDesertMouseEntered

    private void LfDesertMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LfDesertMouseExited
         LfDesert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/desert.png")));
    }//GEN-LAST:event_LfDesertMouseExited

    private void LfDesertMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LfDesertMousePressed
        game.stop();
        initComponents();
        game=new Game(game.board=new FieryDesert());
        game.requestFocus();
        //game.start();
    }//GEN-LAST:event_LfDesertMousePressed

    private void LeRealmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeRealmMouseEntered
         LeRealm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/realm2.png")));
    }//GEN-LAST:event_LeRealmMouseEntered

    private void LeRealmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeRealmMouseExited
        LeRealm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/realm.png")));
    }//GEN-LAST:event_LeRealmMouseExited

    private void LeRealmMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeRealmMousePressed
        game.stop();
        initComponents();
        game=new Game(game.board=new EnchantedRealm());
        game.requestFocus();
        //game.start();
    }//GEN-LAST:event_LeRealmMousePressed

    private void LiIslandMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LiIslandMouseEntered
        LiIsland.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/island2.png")));
    }//GEN-LAST:event_LiIslandMouseEntered

    private void LiIslandMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LiIslandMouseExited
        LiIsland.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/island.png")));
    }//GEN-LAST:event_LiIslandMouseExited

    private void LiIslandMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LiIslandMousePressed
        game.stop();
        initComponents();
        game=new Game(game.board=new IsolatedIsland());
        game.requestFocus();
        //game.start();
    }//GEN-LAST:event_LiIslandMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LeRealm;
    private javax.swing.JLabel LfDesert;
    private javax.swing.JLabel LfKingdom;
    private javax.swing.JLabel LiIsland;
    private javax.swing.JLabel LloadButton;
    private javax.swing.JLabel LsaveButton;
    private javax.swing.JLabel LtitleCenarios;
    private GUI.Game game;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textBombs;
    private javax.swing.JLabel textLives;
    private javax.swing.JLabel textScore;
    private javax.swing.JLabel titleBombs;
    private javax.swing.JLabel titleLives;
    private javax.swing.JLabel titlePlayer;
    private javax.swing.JLabel titleScore;
    // End of variables declaration//GEN-END:variables

    private void myComponents() {
        textScore.setText(""+game.player.getScore());
        textLives.setText(""+game.player.getLives());
        textBombs.setText(""+game.player.getBombs());
    }
}
